---
- name: Create Zsh folder
  file: path=/home/{{ username }}/.zsh state=directory

- name: Get antigen from git
  get_url: url=git.io/antigen dest=/home/{{ username }}/.zsh/antigen.zsh

- name: Upload antigen configuration
  copy: src=dot-antigenrc dest=/home/{{ username }}/.antigenrc
