---
- name: Ensure package dependancies are installed
  become: yes
  pacman:
    name:
      - zsh
      - autojump
      - git

- name: Ensure folders are present
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ ansible_env.HOME }}/.zsh"
    - "{{ ansible_env.HOME }}/.config"

# Should download from git.io/antigen but the redirection seems to break TODO: Check redirection support for get_url
- name: Get antigen from git
  get_url:
    url: https://raw.githubusercontent.com/zsh-users/antigen/master/bin/antigen.zsh
    dest: "{{ ansible_env.HOME }}/.zsh/antigen.zsh"

- name: Upload antigen configuration
  copy:
    src: dot-antigenrc
    dest: "{{ ansible_env.HOME }}/.config/.antigenrc"

- name: Upload zsh configuration
  template:
    src: dot-zshrc.j2
    dest: "{{ ansible_env.HOME }}/.zshrc"

- name: Enforce zsh as default shell
  become: yes
  command: chsh -s /usr/bin/zsh {{ ansible_user }}

- name: Get base16-shell from git
  git:
    repo: "https://github.com/chriskempson/base16-shell.git"
    dest: "{{ ansible_env.HOME }}/.config/base16-shell"
  when: shell_base16_enabled is defined and shell_base16_enabled

- name: Ensure zsh exported functions are presents
  copy:
    src: functions-ansible_dotfiles.zsh
    dest: "{{ ansible_env.HOME }}/.zsh/functions-ansible_dotfiles.zsh"
  when: export_ansible_functions  is defined and export_ansible_functions

- name: Ensure aliases are presents and up to date
  copy:
    src: aliases.zsh
    dest: "{{ ansible_env.HOME }}/.zsh/aliases.zsh"

- include_tasks: fzf.yml
