---

- name: Ensure google linux key is present
  become: yes
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: Ensure google-chrome repository is present in apt
  become: yes
  apt_repository:
    repo: deb http://dl.google.com/linux/chrome/deb/ stable main

- name: Update apt
  become: yes
  apt: update_cache=yes

- name: Install apt packages
  become: yes
  apt:
    pkg:
      - ack  # grep, but better for programmer
      - aria2  # Nice cli download threader / torrent downloader
      - autojump  # Used in conjunction with zsh to autojump
      - bat  # Better cat
      - clipit  # Allow me to copy paste content with shell pipe
      - curl
      - feh  # Image viewer, used to set desktop background
      - flameshot  # For screenshots
      - fzf  # Fuzzy interface
      - git
      - google-chrome-stable
      - grc  # Colorise cli commands like ping ls etc
      - htop
      - httpie  # Modern alternative to curl
      - jq  # JSON manipulation tool
      - lastpass-cli  # lpass
      - make
      - mpv  # Video player
      - python3-virtualenv
      - rxvt-unicode  # urxvt terminal
      - tig  # Git gui full of nice features and tree overview
      - tmate  # Allow instant remote tmux interface like TeamViewer
      - tmux
      - vim
      - visidata  # vd
      - yarn
      - zsh
      - nnn  # Lightweight cli file manager
      - tldr  # Gives examples of common commands
      - pandoc  # Convert doc
      - texlive-latex-base  # (texlive*) Required for pandoc md to pdf
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - anki  # flashcard app

- name: Install packages from snap
  become: yes
  snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic }}"
  loop:
    - { 'name': 'code', 'classic': 'yes' }
    - { 'name': 'go', 'classic': 'yes' }
