---

- name: Ensure google linux key is present
  become: yes
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: Ensure google-chrome repository is present in apt
  become: yes
  apt_repository:
    repo: deb http://dl.google.com/linux/chrome/deb/ stable main

- name: Update apt
  become: yes
  apt: update_cache=yes

- name: Install apt packages
  become: yes
  apt:
    pkg:
      - ack
      - aria2
      - autojump
      - bat
      - clipit
      - curl
      - feh
      - flameshot
      - fzf
      - git
      - google-chrome-stable
      - grc
      - htop
      - httpie
      - jq
      - lastpass-cli  # lpass
      - make
      - mpv
      - python3-virtualenv
      - rxvt-unicode  # urxvt
      - tig
      - tmate
      - tmux
      - vim
      - visidata  # vd
      - yarn
      - zsh

- name: Install packages from snap
  become: yes
  snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic }}"
  loop:
    - { 'name': 'code', 'classic': 'yes' }
    - { 'name': 'go', 'classic': 'yes' }
