---

- name: Ensure google linux key is present
  become: yes
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: Ensure google-chrome repository is present in apt
  become: yes
  apt_repository:
    repo: deb http://dl.google.com/linux/chrome/deb/ stable main

- name: Update apt
  become: yes
  apt: update_cache=yes

- name: Install apt packages
  become: yes
  apt:
    pkg:
      - google-chrome-stable
      - lastpass-cli  #lpass
      - curl
      - vim
      - git
      - htop
      - zsh
      - rxvt-unicode  #urxvt
      - tmux
      - tmate
      - jq
      - feh
      - clipit
      - fzf
      - ack
      - autojump
      - tig

- name: Install vs-code from snap
  become: yes
  snap:
    name: code
    classic: yes

- name: Install golang from snap
  become: yes
  snap:
    name: go
    classic: yes
