---

- name: Upload Xresources file
  copy:
    src: dot-Xresources
    dest: /home/{{ username }}/.Xresources

- name: Ensure local folders are present
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "/home/{{ username }}/.local/share/fonts/"
    - "/home/{{ username }}/go"
    - "/home/{{ username }}/go/bin"
    - "/home/{{ username }}/go/pkg"
    - "/home/{{ username }}/go/src"

- name: Upload Inconsolata font
  copy:
    src: fonts/
    dest: /home/{{ username }}/.local/share/fonts/
